
package it.lutech.servizio;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-15T15:24:34.549+01:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "operazioneFault", targetNamespace = "http://lutech.it/servizio/")
public class OperazioneFault_Exception extends Exception {
    
    private it.lutech.servizio.OperazioneFault operazioneFault;

    public OperazioneFault_Exception() {
        super();
    }
    
    public OperazioneFault_Exception(String message) {
        super(message);
    }
    
    public OperazioneFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public OperazioneFault_Exception(String message, it.lutech.servizio.OperazioneFault operazioneFault) {
        super(message);
        this.operazioneFault = operazioneFault;
    }

    public OperazioneFault_Exception(String message, it.lutech.servizio.OperazioneFault operazioneFault, Throwable cause) {
        super(message, cause);
        this.operazioneFault = operazioneFault;
    }

    public it.lutech.servizio.OperazioneFault getFaultInfo() {
        return this.operazioneFault;
    }
}
