
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package it.lutech.servizio;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-15T15:24:34.562+01:00
 * Generated source version: 3.1.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "servizio",
                      portName = "servizioSOAP",
                      targetNamespace = "http://lutech.it/servizio/",
                      wsdlLocation = "classpath:wsdl/servizio.wsdl",
                      endpointInterface = "it.lutech.servizio.Servizio")
                      
public class ServizioSOAPImpl implements Servizio {

    private static final Logger LOG = Logger.getLogger(ServizioSOAPImpl.class.getName());

    /* (non-Javadoc)
     * @see it.lutech.servizio.Servizio#operazione(it.lutech.servizio.Operazione parameters)*
     */
    public it.lutech.servizio.OperazioneResponse operazione(Operazione parameters) throws OperazioneFault_Exception   { 
        LOG.info("Executing operation operazione");
        System.out.println(parameters);
        try {
            it.lutech.servizio.OperazioneResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new OperazioneFault_Exception("operazioneFault...");
    }

}
