
package it.lutech.servizio;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-15T15:24:34.581+01:00
 * Generated source version: 3.1.10
 * 
 */
 
public class Servizio_ServizioSOAP_Server{

    protected Servizio_ServizioSOAP_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ServizioSOAPImpl();
        String address = "http://lutech.it/servizio";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new Servizio_ServizioSOAP_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
