
package it.lutech.servizio;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-15T15:24:34.534+01:00
 * Generated source version: 3.1.10
 * 
 */
public final class Servizio_ServizioSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://lutech.it/servizio/", "servizio");

    private Servizio_ServizioSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Servizio_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Servizio_Service ss = new Servizio_Service(wsdlURL, SERVICE_NAME);
        Servizio port = ss.getServizioSOAP();  
        
        {
        System.out.println("Invoking operazione...");
        it.lutech.servizio.Operazione _operazione_parameters = null;
        try {
            it.lutech.servizio.OperazioneResponse _operazione__return = port.operazione(_operazione_parameters);
            System.out.println("operazione.result=" + _operazione__return);

        } catch (OperazioneFault_Exception e) { 
            System.out.println("Expected exception: operazioneFault has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
