package it.lutech.servizio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-15T15:24:34.574+01:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://lutech.it/servizio/", name = "servizio")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Servizio {

    @WebMethod(action = "http://lutech.it/servizio/operazione")
    @WebResult(name = "operazioneResponse", targetNamespace = "http://lutech.it/servizio/", partName = "parameters")
    public OperazioneResponse operazione(
        @WebParam(partName = "parameters", name = "operazione", targetNamespace = "http://lutech.it/servizio/")
        Operazione parameters
    ) throws OperazioneFault_Exception;
}
