
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package net.webservicex;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-15T15:07:15.818+01:00
 * Generated source version: 3.1.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "GlobalWeather",
                      portName = "GlobalWeatherHttpPost",
                      targetNamespace = "http://www.webserviceX.NET",
                      wsdlLocation = "file:/C:/Users/andre/Desktop/Temp/Java-Lutech/Guasti-WSClient/src/main/wsdl/globalweather.wsdl",
                      endpointInterface = "net.webservicex.GlobalWeatherHttpPost")
                      
public class GlobalWeatherHttpPostImpl implements GlobalWeatherHttpPost {

    private static final Logger LOG = Logger.getLogger(GlobalWeatherHttpPostImpl.class.getName());

    /* (non-Javadoc)
     * @see net.webservicex.GlobalWeatherHttpPost#getCitiesByCountry(java.lang.String countryName)*
     */
    public java.lang.String getCitiesByCountry(java.lang.String countryName) { 
        LOG.info("Executing operation getCitiesByCountry");
        System.out.println(countryName);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.webservicex.GlobalWeatherHttpPost#getWeather(java.lang.String cityName, java.lang.String countryName)*
     */
    public java.lang.String getWeather(java.lang.String cityName, java.lang.String countryName) { 
        LOG.info("Executing operation getWeather");
        System.out.println(cityName);
        System.out.println(countryName);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
