
package net.webservicex;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-15T15:07:15.900+01:00
 * Generated source version: 3.1.10
 * 
 */
 
public class GlobalWeatherHttpGet_GlobalWeatherHttpGet_Server{

    protected GlobalWeatherHttpGet_GlobalWeatherHttpGet_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new GlobalWeatherHttpGetImpl();
        String address = "http://www.webservicex.net/globalweather.asmx";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new GlobalWeatherHttpGet_GlobalWeatherHttpGet_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
